### ISSUE TITLE
文件上传时报错

### ISSUE THREAD

**Issue by ThornbirdSitcom** [gnuf0rce/Netdisk-FileSync-Plugin#4]
文件上传失败，每次都会弹出类似错误
```
文件 TADST.exe 上传失败, Client request(POST https://pcs.baidu.com/rest/2.0/pcs/superfile2?access_token=121.0500e3f78888348fa34950908ecb73b9.YBm5RGSVFMCxpsfFdH336nWH-w4vlBkT48MSZHA.v0db5g&method=upload&type=tmpfile&path=apps%2FVTNYG%40L52ue7cP~zNzhP5EQyQNrT8ixQ%2F598590488%2FTADST.exe&uploadid=P1-MTAuMjI4LjcwLjMwOjE2NzI5MzI3Njk6MTE1NTI2NDE4NTU3ODUxOTA0&partseq=0) invalid: 400 Bad Request. Text: "{"error_code":31299, "error_msg":"Size of superfile2 first part should not be smaller than 4MB"}"
```
不太清楚是哪里弄错了，所有文件都这样，请求指点，多谢！

**Comment by cssxsh** [comment]
请提供一下插件版本

**Comment by ThornbirdSitcom** [comment]
1.3.6，最新的release那一版

**Comment by cssxsh** [comment]
我更新了 1.3.7 https://github.com/gnuf0rce/Netdisk-FileSync-Plugin/releases/tag/v1.3.7

你先试试这个版本，如果还是保存我再看看是哪里有问题

**Comment by ThornbirdSitcom** [comment]
这次在启动时遇到了问题。
`2023-01-06 11:13:57 W/JvmPluginLoader: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 in https://maven.aliyun.com/repository/central (https://maven.aliyun.com/repository/central)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 in https://maven.aliyun.com/repository/central (https://maven.aliyun.com/repository/central)
2023-01-06 11:14:07 W/JvmPluginLoader: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connect timed out
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.24.209] failed: Connect timed out`
嗯...或许是我哪里没有更新正确？之前我用mcl安装的，我这次用mcl发现mcl还是1.3.6，于是卸载mcl手动加入插件后启动时报这个错。

**Comment by cssxsh** [comment]
> https://maven.aliyun.com/repository/central

阿里云的锅

你可以等一等阿里云同步

**Comment by cssxsh** [comment]
好了吗

**Comment by ThornbirdSitcom** [comment]
似乎阿里云的仓库一直没有更新，我到现在收到的还是1.3.6。

**Comment by cssxsh** [comment]
> 似乎阿里云的仓库一直没有更新，我到现在收到的还是1.3.6。

？

**Comment by cssxsh** [comment]
你不是手动安装的吗

**Comment by ThornbirdSitcom** [comment]
之后我又尝试了mcl安装，那我现在再尝试一次手动安装

**Comment by ThornbirdSitcom** [comment]
手动安装仍然报错，报错内容和我上午发的一致

**Comment by cssxsh** [comment]
确定内容一样？

**Comment by ThornbirdSitcom** [comment]
是的，我确定。需要上传一份完整日志吗？

**Comment by cssxsh** [comment]
我本地测试是没有问题的
方便的话你就上传吧

**Comment by ThornbirdSitcom** [comment]
`==================================[ Mirai consosle 2.13.2 ]===================================
 __       __ __                   __  ______                                      __
|  \     /  \  \                 |  \/      \                                    |  \
| ▓▓\   /  ▓▓\▓▓ ______   ______  \▓▓  ▓▓▓▓▓▓\ ______  _______   _______  ______ | ▓▓ ______
| ▓▓▓\ /  ▓▓▓  \/      \ |      \|  \ ▓▓   \▓▓/      \|       \ /       \/      \| ▓▓/      \
| ▓▓▓▓\  ▓▓▓▓ ▓▓  ▓▓▓▓▓▓\ \▓▓▓▓▓▓\ ▓▓ ▓▓     |  ▓▓▓▓▓▓\ ▓▓▓▓▓▓▓\  ▓▓▓▓▓▓▓  ▓▓▓▓▓▓\ ▓▓  ▓▓▓▓▓▓\
| ▓▓\▓▓ ▓▓ ▓▓ ▓▓ ▓▓   \▓▓/      ▓▓ ▓▓ ▓▓   __| ▓▓  | ▓▓ ▓▓  | ▓▓\▓▓    \| ▓▓  | ▓▓ ▓▓ ▓▓    ▓▓
| ▓▓ \▓▓▓| ▓▓ ▓▓ ▓▓     |  ▓▓▓▓▓▓▓ ▓▓ ▓▓__/  \ ▓▓__/ ▓▓ ▓▓  | ▓▓_\▓▓▓▓▓▓\ ▓▓__/ ▓▓ ▓▓ ▓▓▓▓▓▓▓▓
| ▓▓  \▓ | ▓▓ ▓▓ ▓▓      \▓▓    ▓▓ ▓▓\▓▓    ▓▓\▓▓    ▓▓ ▓▓  | ▓▓       ▓▓\▓▓    ▓▓ ▓▓\▓▓     \
 \▓▓      \▓▓\▓▓\▓▓       \▓▓▓▓▓▓▓\▓▓ \▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓   \▓▓\▓▓▓▓▓▓▓  \▓▓▓▓▓▓ \▓▓ \▓▓▓▓▓▓▓


2023-01-06 14:55:44 I/main: Backend: version 2.13.2, built on 2022-12-05 01:50:53.
2023-01-06 14:55:44 I/main: Frontend Terminal: version 2.13.2, provided by Mamoe Technologies
2023-01-06 14:55:44 I/main: Welcome to visit https://mirai.mamoe.net/
2023-01-06 14:55:44 W/stderr: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2023-01-06 14:55:44 W/stderr: SLF4J: Defaulting to no-operation (NOP) logger implementation
2023-01-06 14:55:44 W/stderr: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin AntiRecall v1.0.3
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin Chat Command v0.5.0
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin net.mamoe.mirai-api-http v2.6.2
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin mirai-device-generator v1.1.3
2023-01-06 14:55:46 W/stderr: ERROR StatusLogger Log4j2 could not find a logging implementation. Please add log4j-core to the classpath. Using SimpleLogger to log to the console...
2023-01-06 14:55:46 I/WindowHelperJvm: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
2023-01-06 14:55:46 I/WindowHelperJvm: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin mirai-login-solver-sakura v0.0.7
2023-01-06 14:55:46 I/plugin: Successfully loaded plugin MCL Addon v2.1.1
2023-01-06 14:55:47 W/JvmPluginLoader: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 in https://maven.aliyun.com/repository/central (https://maven.aliyun.com/repository/central)
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 in https://maven.aliyun.com/repository/central (https://maven.aliyun.com/repository/central)
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginDependencyDownloader.resolveDependencies(JvmPluginDependencyDownload.kt:270)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkLibraries(JvmPluginClassLoader.kt:338)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginSharedLibraries$mirai_console(JvmPluginClassLoader.kt:304)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginLibraries(JvmPluginClassLoader.kt:326)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:280)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:90)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:146)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:279)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)

2023-01-06 14:55:57 W/JvmPluginLoader: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginDependencyDownloader.resolveDependencies(JvmPluginDependencyDownload.kt:270)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkLibraries(JvmPluginClassLoader.kt:338)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginSharedLibraries$mirai_console(JvmPluginClassLoader.kt:304)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginLibraries(JvmPluginClassLoader.kt:326)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:280)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:90)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:146)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:279)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:316)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:272)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	... 35 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 48 more

2023-01-06 14:55:57 I/plugin: Cannot load plugin file-sync v1.3.7
2023-01-06 14:55:57 E/main: Failed to init MiraiConsole.
net.mamoe.mirai.console.plugin.loader.PluginLoadException: Exception while loading file-sync v1.3.7
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:285)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:35)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt)
	at net.mamoe.mirai.console.plugin.jvm.JvmPluginLoader$BuiltIn.load(JvmPluginLoader.kt:50)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadPluginNoEnable(PluginManagerImpl.kt:90)
	at net.mamoe.mirai.console.internal.plugin.PluginManagerImpl.loadAllPluginsUsingBuiltInLoaders$mirai_console(PluginManagerImpl.kt:146)
	at net.mamoe.mirai.console.internal.MiraiConsoleImplementationBridge.doStart$mirai_console(MiraiConsoleImplementationBridge.kt:279)
	at net.mamoe.mirai.console.MiraiConsoleImplementation$Companion.start(MiraiConsoleImplementation.kt:508)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon(MiraiConsoleTerminalLoader.kt:177)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.startAsDaemon$default(MiraiConsoleTerminalLoader.kt:176)
	at net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader.main(MiraiConsoleTerminalLoader.kt:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:86)
	at org.itxtech.mcl.Utility.bootJars(Utility.java:76)
	at org.itxtech.mcl.Utility.bootMirai(Utility.java:98)
	at org.itxtech.mcl.module.builtin.Boot.boot(Boot.java:113)
	at org.itxtech.mcl.module.ModuleManager.phaseBoot(ModuleManager.java:123)
	at org.itxtech.mcl.Loader.lambda$start$4(Loader.java:196)
	at org.itxtech.mcl.Loader.tryCatching(Loader.java:151)
	at org.itxtech.mcl.Loader.start(Loader.java:196)
	at org.itxtech.mcl.Loader.main(Loader.java:84)
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:374)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginDependencyDownloader.resolveDependencies(JvmPluginDependencyDownload.kt:270)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkLibraries(JvmPluginClassLoader.kt:338)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginSharedLibraries$mirai_console(JvmPluginClassLoader.kt:304)
	at net.mamoe.mirai.console.internal.plugin.JvmPluginClassLoaderN.linkPluginLibraries(JvmPluginClassLoader.kt:326)
	at net.mamoe.mirai.console.internal.plugin.BuiltInJvmPluginLoaderImpl.load(BuiltInJvmPluginLoaderImpl.kt:280)
	... 23 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:431)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:235)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	... 28 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact xyz.cssxsh.baidu:baidu-netdisk:jar:3.3.0 from/to https://repo1.maven.org/maven2/ (https://repo1.maven.org/maven2/): Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:52)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
	at org.eclipse.aether.util.concurrency.RunnableErrorForwarder.lambda$wrap$0(RunnableErrorForwarder.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:627)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:408)
	... 30 more
Caused by: org.apache.http.conn.ConnectTimeoutException: Connect to repo1.maven.org:443 [repo1.maven.org/151.101.40.209] failed: Connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.eclipse.aether.transport.http.HttpTransporter.execute(HttpTransporter.java:316)
	at org.eclipse.aether.transport.http.HttpTransporter.implGet(HttpTransporter.java:272)
	at org.eclipse.aether.spi.connector.transport.AbstractTransporter.get(AbstractTransporter.java:73)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$GetTaskRunner.runTask(BasicRepositoryConnector.java:457)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:364)
	... 35 more
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 48 more`

**Comment by cssxsh** [comment]
阿里云不太行

你可以编辑一下源地址 `mcl/config/Console/PluginDependencies.yml`
里加上 华为的源
`https://repo.huaweicloud.com/repository/maven`

**Comment by ThornbirdSitcom** [comment]
这一次倒是启动成功了，不过上传文件时和昨晚报错一样了。
我注意到一点，现在百度验证会说“您遇到了错误”，而以前是可以出二维码扫描的
错误代码：invalid_scope
错误信息：scope is invalid
详细描述：所请求的扩展权限尚未开放，关于权限的具体信息请开发者参考“权限列表”

会不会是我的申请哪里出错了呢？

**Comment by cssxsh** [comment]
> 这一次倒是启动成功了，不过上传文件时和昨晚报错一样了。 我注意到一点，现在百度验证会说“您遇到了错误”，而以前是可以出二维码扫描的 错误代码：invalid_scope 错误信息：scope is invalid 详细描述：所请求的扩展权限尚未开放，关于权限的具体信息请开发者参考“权限列表”
> 
> 会不会是我的申请哪里出错了呢？

不知道，可能是你复制 oauth 链接的时候没复制全

**Comment by ThornbirdSitcom** [comment]
OK，现在成功了，都可以上传了。
重启了一下机器人就正常了，不知道为什么，尽管再次尝试验证还是失败，但利用baidu user命令是可以看到用户信息的，上传也正常了，可能已经登陆成功了就不能再次调用接口了？不确定。
方便再请问一下文件存贮在哪里么？没有在云盘的根目录看到，但秒传码是有的。
真心感谢前辈的指点和付出！祝前辈之后的开发之路一路顺利！

**Comment by cssxsh** [comment]
文件在 [我的应用数据](https://pan.baidu.com/disk/main#/index?category=all&path=%2Fapps) 里面

**Comment by ThornbirdSitcom** [comment]
好的，十分感谢！
